name: Release

on:
  push:
    tags:
      - '*'
jobs:
  Release:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install dependencies
        run: bundle install
      - name: Extract version from tag name
        id: extract_version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=$(echo "$TAG_NAME" | sed 's/^v//')
          echo "::set-output name=version::$VERSION"
      - name: Build gem
        run: |
          gem build test-rc-sdk.gemspec
      - name: Publish gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          gem push test-rc-sdk-${{ steps.extract_version.outputs.version }}.gem --host https://rubygems.org
